name: 🐞 Bug
description: Report a bug
title: "[BUG] <title>"
labels: [Bug]
body:
- type: markdown
  attributes:
    value: "#### *Thanks for taking the time to fill out this bug.*"
    
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true

- type: markdown
  attributes:
    value: "#### Please ensure that all required (*) fields are filled out in order to submit the issue."
    
- type: textarea
  id: description
  attributes:
    label: "Description"
    description: Please enter an explicit description of your bug
    placeholder: Short and explicit description of the bug...
  validations:
    required: true     
    
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  validations:
    required: false
    
- type: textarea
  id: screenshot
  attributes:
    label: "Screenshots"
    description: If applicable, add screenshots to show the bug.
    value: |
      ![DESCRIPTION](LINK.png)
    render: bash
  validations:
    required: false
    
- type: dropdown
  id: browsers
  attributes:
    label: What browsers are you seeing the problem on?
    multiple: true
    options:
      - Firefox
      - Chrome
      - Safari
      - Microsoft Edge
      - Opera
      
- type: dropdown
  id: os
  attributes:
    label: "OS"
    description: In which OS, you found the bug?
    multiple: true
    options:
      - Windows
      - Linux
      - Mac
  validations:
    required: false

- type: checkboxes
  attributes:
    label: Have you provided all details?
    description: Please ensure that you provide us all details relating to the bug.
    options:
    - label: Yes, I have provided as much detail as possible
      required: true