name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint:eslint

      - name: Run Prettier
        run: npm run lint:prettier

      - name: Run stylelint
        run: npm run lint:stylelint

      - name: Fail if there are lint errors
        if: ${{ steps.lint:eslint.outcome == 'failure' || steps.lint:prettier.outcome == 'failure' || steps.lint:stylelint.outcome == 'failure' }}
        run: exit 1
